name: Test package

on: [ push, pull_request ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.7.8"
        enable-cache: true

    - name: "Set up Python"
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run tests with coverage
      run: |
        uv run -m pytest

    - name: Run Ruff
      run: uv run ruff check --output-format=github --select E4,E7,E9,F
